# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/butchertd/Documents/eaglesat/CRP_VIVADO_FPGA/uart_testing/uart_testing.srcs/sources_1/bd/fpga_design/ip/fpga_design_fifo_generator_1_0/fpga_design_fifo_generator_1_0.xci
# IP: The module: 'fpga_design_fifo_generator_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/butchertd/Documents/eaglesat/CRP_VIVADO_FPGA/uart_testing/uart_testing.srcs/sources_1/bd/fpga_design/ip/fpga_design_fifo_generator_1_0/fpga_design_fifo_generator_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_design_fifo_generator_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/butchertd/Documents/eaglesat/CRP_VIVADO_FPGA/uart_testing/uart_testing.srcs/sources_1/bd/fpga_design/ip/fpga_design_fifo_generator_1_0/fpga_design_fifo_generator_1_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_design_fifo_generator_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/butchertd/Documents/eaglesat/CRP_VIVADO_FPGA/uart_testing/uart_testing.srcs/sources_1/bd/fpga_design/ip/fpga_design_fifo_generator_1_0/fpga_design_fifo_generator_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_design_fifo_generator_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/butchertd/Documents/eaglesat/CRP_VIVADO_FPGA/uart_testing/uart_testing.srcs/sources_1/bd/fpga_design/ip/fpga_design_fifo_generator_1_0/fpga_design_fifo_generator_1_0.xci
# IP: The module: 'fpga_design_fifo_generator_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/butchertd/Documents/eaglesat/CRP_VIVADO_FPGA/uart_testing/uart_testing.srcs/sources_1/bd/fpga_design/ip/fpga_design_fifo_generator_1_0/fpga_design_fifo_generator_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_design_fifo_generator_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/butchertd/Documents/eaglesat/CRP_VIVADO_FPGA/uart_testing/uart_testing.srcs/sources_1/bd/fpga_design/ip/fpga_design_fifo_generator_1_0/fpga_design_fifo_generator_1_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_design_fifo_generator_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/butchertd/Documents/eaglesat/CRP_VIVADO_FPGA/uart_testing/uart_testing.srcs/sources_1/bd/fpga_design/ip/fpga_design_fifo_generator_1_0/fpga_design_fifo_generator_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpga_design_fifo_generator_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
