set_property IOSTANDARD LVCMOS33 [get_ports pixClk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {cameraid[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cameraid[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imgData[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imgData[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imgData[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imgData[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imgData[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imgData[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imgData[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imgData[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imgData[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imgData[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imgData[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imgData[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports Camera_clk]
set_property PACKAGE_PIN A15 [get_ports {cameraid[0]}]
set_property PACKAGE_PIN B15 [get_ports {cameraid[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports layerid]
set_property IOSTANDARD LVCMOS33 [get_ports Tx]
set_property IOSTANDARD LVCMOS33 [get_ports sim_enable]
set_property IOSTANDARD LVCMOS33 [get_ports Rx]
set_property PACKAGE_PIN N2 [get_ports Tx]
set_property PACKAGE_PIN M3 [get_ports sim_enable]
set_property PACKAGE_PIN N1 [get_ports Rx]
set_property PACKAGE_PIN H1 [get_ports layerid]
set_property PACKAGE_PIN U2 [get_ports Camera_clk]
set_property PACKAGE_PIN L17 [get_ports pixClk]
set_property PACKAGE_PIN V4 [get_ports rst]
set_property PACKAGE_PIN V2 [get_ports clk]


set_property IOSTANDARD LVCMOS33 [get_ports fifo_ready]
set_property PACKAGE_PIN J3 [get_ports fifo_ready]

set_property IOSTANDARD LVCMOS33 [get_ports rx_out]
set_property PACKAGE_PIN J1 [get_ports rx_out]

set_property IOSTANDARD LVCMOS33 [get_ports {dout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[0]}]
set_property PACKAGE_PIN R3 [get_ports {dout[0]}]
set_property PACKAGE_PIN T3 [get_ports {dout[1]}]
set_property PACKAGE_PIN R2 [get_ports {dout[2]}]
set_property PACKAGE_PIN T1 [get_ports {dout[3]}]
set_property PACKAGE_PIN T2 [get_ports {dout[4]}]
set_property PACKAGE_PIN U1 [get_ports {dout[5]}]
set_property PACKAGE_PIN W2 [get_ports {dout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[7]}]
set_property PACKAGE_PIN V2 [get_ports {dout[7]}]
