# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ew.xdc

# Block Designs: bd/fpga_design/fpga_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_design || ORIG_REF_NAME==fpga_design} -quiet] -quiet

# IP: bd/fpga_design/ip/fpga_design_central_interface_0_0/fpga_design_central_interface_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_design_central_interface_0_0 || ORIG_REF_NAME==fpga_design_central_interface_0_0} -quiet] -quiet

# IP: bd/fpga_design/ip/fpga_design_uart_tx_0_0/fpga_design_uart_tx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_design_uart_tx_0_0 || ORIG_REF_NAME==fpga_design_uart_tx_0_0} -quiet] -quiet

# IP: bd/fpga_design/ip/fpga_design_fifo_protector_0_0/fpga_design_fifo_protector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_design_fifo_protector_0_0 || ORIG_REF_NAME==fpga_design_fifo_protector_0_0} -quiet] -quiet

# IP: bd/fpga_design/ip/fpga_design_threshold_memory_0_0/fpga_design_threshold_memory_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_design_threshold_memory_0_0 || ORIG_REF_NAME==fpga_design_threshold_memory_0_0} -quiet] -quiet

# IP: bd/fpga_design/ip/fpga_design_image_thresholding_0_0/fpga_design_image_thresholding_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_design_image_thresholding_0_0 || ORIG_REF_NAME==fpga_design_image_thresholding_0_0} -quiet] -quiet

# IP: bd/fpga_design/ip/fpga_design_uart_rx_0_0/fpga_design_uart_rx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_design_uart_rx_0_0 || ORIG_REF_NAME==fpga_design_uart_rx_0_0} -quiet] -quiet

# IP: bd/fpga_design/ip/fpga_design_camera_simulator_0_0/fpga_design_camera_simulator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_design_camera_simulator_0_0 || ORIG_REF_NAME==fpga_design_camera_simulator_0_0} -quiet] -quiet

# IP: bd/fpga_design/ip/fpga_design_UART_clk_gen_0_0/fpga_design_UART_clk_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_design_UART_clk_gen_0_0 || ORIG_REF_NAME==fpga_design_UART_clk_gen_0_0} -quiet] -quiet

# IP: bd/fpga_design/ip/fpga_design_fifo_generator_1_0/fpga_design_fifo_generator_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_design_fifo_generator_1_0 || ORIG_REF_NAME==fpga_design_fifo_generator_1_0} -quiet] -quiet

# XDC: bd/fpga_design/fpga_design_ooc.xdc
